### ISSUE TITLE
Ubuntu 20.04 LTS don not compiles

### ISSUE THREAD

**Issue by leoelan** [junjunk/lisg#6]
root@leo:/opt/lisg/kernel# ./configure 
Kernel version: 5.4.0-42-generic
Iptables binary version: 1.8.4 (legacy) (detected from /usr/sbin/iptables)
Searching for iptables-1.8.4 (legacy) sources..
Found iptables sources at /usr
Iptables module path: /usr/lib/debug/.dwz/x86_64-linux-gnu/iptables.debug (from binary)
Creating Makefile.. done.

Now run: 'make' and (if everything is fine) 'make install'

root@leo:/opt/lisg/kernel# make && make install 
echo "" > build.h
printf "/* Compilation date.\n * Written by Makefile (userspace) */\n#define _BUILD_DATE \"%s %s\"\n" `date +'%F %T'` > build.h
make -C /lib/modules/5.4.0-42-generic/build M=/opt/lisg/kernel modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-42-generic'
  CC [M]  /opt/lisg/kernel/isg_main.o
  LD [M]  /opt/lisg/kernel/ipt_ISG.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC [M]  /opt/lisg/kernel/ipt_ISG.mod.o
  LD [M]  /opt/lisg/kernel/ipt_ISG.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-42-generic'
gcc -O2 -Wall -Wunused -I/include -DIPTABLES_VERSION=\"1.8.4 (legacy)\"  -fPIC -o libipt_ISG_sh.o -c libipt_isg.c
/bin/sh: 1: Syntax error: "(" unexpected
make: *** [Makefile:17: all] Error 2

root@leo:/opt/lisg/kernel# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
root@leo:/opt/lisg/kernel#

**Comment by vvfedorenko** [comment]
Ubuntu 22.04 works fine, but I'll change the way it checks and extracts iptables version

**Comment by vvfedorenko** [comment]
The issue was fixed
