### ISSUE TITLE
Debian 11 не подключается к модулю

### ISSUE THREAD

**Issue by TTpartizan** [junjunk/lisg#7]
debian 11 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux5.10.179-1 (2023-05-12) x86_64 GNU/Linux 
lsmod | grep ISG
ipt_ISG                28672  0
x_tables               53248  13 xt_conntrack,iptable_filter,xt_LOG,xt_state,ipt_NETFLOW,xt_nat,ipt_ISG,xt_set,ipt_REJECT,ip_tables,xt_limit,xt_connlimit,iptable_mangle
iptables v1.8.7 (legacy)

Модуль собрался - загрузился, но получаю такое
./ISG.pl
Incorrect packet length (196 bytes)
Recv from kernel: Interrupted system call
Unable to get sessions/services list: Interrupted system call

**Comment by vvfedorenko** [comment]
the issue is fixed in the latest commits
